version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server.log:/app/server.log
    environment:
      - PORT=$PORT
    depends_on:
      - mongo
  nginx:
    image: nginx
    environment:
      - PORT=$PORT
      - NAME=$NAME
    ports:
      - "80:80"
    volumes:
      - ./nginx.template.conf:/etc/nginx/templates/nginx.template.conf
    command: /bin/sh -c "envsubst < /etc/nginx/templates/nginx.template.conf > /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"  



